// <auto-generated />
using System;
using ChordCraft.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChordCraft.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318215517_SeedPhases2to5")]
    partial class SeedPhases2to5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChordCraft.Core.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Criteria = "{\"type\":\"first-lesson\"}",
                            Description = "Complete your first lesson",
                            IconUrl = "/images/badges/first-steps.svg",
                            Name = "First Steps"
                        },
                        new
                        {
                            Id = 2,
                            Criteria = "{\"type\":\"phase-complete\",\"phaseId\":1}",
                            Description = "Complete Phase 1",
                            IconUrl = "/images/badges/switch-basics.svg",
                            Name = "Switch Basics"
                        },
                        new
                        {
                            Id = 3,
                            Criteria = "{\"type\":\"phase-complete\",\"phaseId\":2}",
                            Description = "Complete Phase 2",
                            IconUrl = "/images/badges/direction-master.svg",
                            Name = "Direction Master"
                        },
                        new
                        {
                            Id = 4,
                            Criteria = "{\"type\":\"speed-threshold\",\"wpm\":20}",
                            Description = "Reach 20 WPM in a practice lesson",
                            IconUrl = "/images/badges/speed-demon.svg",
                            Name = "Speed Demon"
                        },
                        new
                        {
                            Id = 5,
                            Criteria = "{\"type\":\"first-chord\"}",
                            Description = "Successfully type your first chord",
                            IconUrl = "/images/badges/first-chord.svg",
                            Name = "First Chord"
                        },
                        new
                        {
                            Id = 6,
                            Criteria = "{\"type\":\"chord-count\",\"count\":10}",
                            Description = "Learn 10 different chords",
                            IconUrl = "/images/badges/chord-collector.svg",
                            Name = "Chord Collector"
                        },
                        new
                        {
                            Id = 7,
                            Criteria = "{\"type\":\"chord-count\",\"count\":50}",
                            Description = "Learn 50 different chords",
                            IconUrl = "/images/badges/chord-master.svg",
                            Name = "Chord Master"
                        },
                        new
                        {
                            Id = 8,
                            Criteria = "{\"type\":\"streak\",\"days\":5}",
                            Description = "Practice 5 days in a row",
                            IconUrl = "/images/badges/5-day-streak.svg",
                            Name = "5 Day Streak"
                        },
                        new
                        {
                            Id = 9,
                            Criteria = "{\"type\":\"weekend\"}",
                            Description = "Practice on Saturday and Sunday",
                            IconUrl = "/images/badges/weekend-warrior.svg",
                            Name = "Weekend Warrior"
                        },
                        new
                        {
                            Id = 10,
                            Criteria = "{\"type\":\"session-time\",\"minutes\":30}",
                            Description = "Practice for 30 minutes in one session",
                            IconUrl = "/images/badges/marathon-runner.svg",
                            Name = "Marathon Runner"
                        },
                        new
                        {
                            Id = 11,
                            Criteria = "{\"type\":\"star-count\",\"stars\":5,\"count\":10}",
                            Description = "Earn 5 stars on 10 lessons",
                            IconUrl = "/images/badges/perfectionist.svg",
                            Name = "Perfectionist"
                        },
                        new
                        {
                            Id = 12,
                            Criteria = "{\"type\":\"full-layout\"}",
                            Description = "Show proficiency on all 90 CCOS inputs",
                            IconUrl = "/images/badges/full-layout.svg",
                            Name = "Full Layout"
                        },
                        new
                        {
                            Id = 13,
                            Criteria = "{\"type\":\"daily-stars\",\"stars\":5,\"count\":5}",
                            Description = "Earn 5 stars on 5 lessons in one day",
                            IconUrl = "/images/badges/heavyweight.svg",
                            Name = "The Heavyweight"
                        },
                        new
                        {
                            Id = 14,
                            Criteria = "{\"type\":\"attempt-count\",\"count\":100}",
                            Description = "Rack up 100 total lesson attempts",
                            IconUrl = "/images/badges/keyboard-crusher.svg",
                            Name = "Keyboard Crusher"
                        });
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.ChordEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("InputKeys")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OutputText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChordEntries");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<decimal>("PassAccuracyThreshold")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<int>("PhaseId")
                        .HasColumnType("integer");

                    b.Property<int?>("SpeedGoal")
                        .HasColumnType("integer");

                    b.Property<string>("TargetInputs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "{\"videoUrl\":\"/videos/intro.mp4\",\"durationSeconds\":120,\"completionThreshold\":0.9}",
                            Description = "Learn what the CharaChorder One is and how to hold it",
                            Number = 1,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[]",
                            Title = "Introduction to CharaChorder",
                            Type = 4
                        },
                        new
                        {
                            Id = 2,
                            Content = "{\"steps\":[{\"instruction\":\"Push the left index switch down to type f\",\"targetInput\":\"L_Index:Push\",\"targetChar\":\"f\"}]}",
                            Description = "Push the left index switch to type f",
                            Number = 2,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Index:Push\"]",
                            Title = "Left Index Push: f",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Content = "{\"steps\":[{\"instruction\":\"Push the right index switch down to type j\",\"targetInput\":\"R_Index:Push\",\"targetChar\":\"j\"}]}",
                            Description = "Push the right index switch to type j",
                            Number = 3,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"R_Index:Push\"]",
                            Title = "Right Index Push: j",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Content = "{\"sequence\":[\"f\",\"j\",\"f\",\"j\",\"f\",\"f\",\"j\",\"j\",\"f\",\"j\",\"j\",\"f\",\"f\",\"j\",\"f\",\"j\",\"j\",\"f\",\"j\",\"f\"]}",
                            Description = "Practice typing f and j",
                            Number = 4,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Index:Push\",\"R_Index:Push\"]",
                            Title = "Review: f & j",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "{\"steps\":[{\"instruction\":\"Push the left thumb switch to type a space\",\"targetInput\":\"L_Thumb:Push\",\"targetChar\":\" \"}]}",
                            Description = "Push the left thumb switch for space",
                            Number = 5,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Thumb:Push\"]",
                            Title = "Space (Left Thumb Push)",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Content = "{\"steps\":[{\"instruction\":\"Push the left middle switch down to type d\",\"targetInput\":\"L_Middle:Push\",\"targetChar\":\"d\"}]}",
                            Description = "Push the left middle switch to type d",
                            Number = 6,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Middle:Push\"]",
                            Title = "Left Middle Push: d",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Content = "{\"steps\":[{\"instruction\":\"Push the right middle switch down to type k\",\"targetInput\":\"R_Middle:Push\",\"targetChar\":\"k\"}]}",
                            Description = "Push the right middle switch to type k",
                            Number = 7,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"R_Middle:Push\"]",
                            Title = "Right Middle Push: k",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Content = "{\"sequence\":[\"d\",\"k\",\"d\",\"k\",\"d\",\"d\",\"k\",\"k\",\"d\",\"k\",\"k\",\"d\",\"d\",\"k\",\"d\",\"k\",\"k\",\"d\",\"k\",\"d\"]}",
                            Description = "Practice typing d and k",
                            Number = 8,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Middle:Push\",\"R_Middle:Push\"]",
                            Title = "Review: d & k",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Content = "{\"text\":\"f j d k f k d j f d k j d f j k f j d k\",\"timeLimitSeconds\":120}",
                            Description = "Practice all four keys together",
                            Number = 9,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            SpeedGoal = 5,
                            TargetInputs = "[\"L_Index:Push\",\"R_Index:Push\",\"L_Middle:Push\",\"R_Middle:Push\"]",
                            Title = "Practice: f j d k",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Content = "{\"steps\":[{\"instruction\":\"Push the left ring switch down to type s\",\"targetInput\":\"L_Ring:Push\",\"targetChar\":\"s\"}]}",
                            Description = "Push the left ring switch to type s",
                            Number = 10,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Ring:Push\"]",
                            Title = "Left Ring Push: s",
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            Content = "{\"steps\":[{\"instruction\":\"Push the right ring switch down to type l\",\"targetInput\":\"R_Ring:Push\",\"targetChar\":\"l\"}]}",
                            Description = "Push the right ring switch to type l",
                            Number = 11,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"R_Ring:Push\"]",
                            Title = "Right Ring Push: l",
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Content = "{\"steps\":[{\"instruction\":\"Push the left pinky switch down to type a\",\"targetInput\":\"L_Pinky:Push\",\"targetChar\":\"a\"}]}",
                            Description = "Push the left pinky switch to type a",
                            Number = 12,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Pinky:Push\"]",
                            Title = "Left Pinky Push: a",
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Content = "{\"steps\":[{\"instruction\":\"Push the right pinky switch down to type ;\",\"targetInput\":\"R_Pinky:Push\",\"targetChar\":\";\"}]}",
                            Description = "Push the right pinky switch to type ;",
                            Number = 13,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"R_Pinky:Push\"]",
                            Title = "Right Pinky Push: ;",
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            Content = "{\"sequence\":[\"a\",\"s\",\"d\",\"f\",\"j\",\"k\",\"l\",\";\",\"f\",\"j\",\"a\",\";\",\"s\",\"l\",\"d\",\"k\"]}",
                            Description = "Review all finger push inputs",
                            Number = 14,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Pinky:Push\",\"L_Ring:Push\",\"L_Middle:Push\",\"L_Index:Push\",\"R_Index:Push\",\"R_Middle:Push\",\"R_Ring:Push\",\"R_Pinky:Push\"]",
                            Title = "All Push Keys",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Content = "{\"gameType\":\"falling-characters\",\"timeLimitSeconds\":60,\"wordPool\":[\"a\",\"s\",\"d\",\"f\",\"j\",\"k\",\"l\",\";\"]}",
                            Description = "Game challenge with push keys",
                            Number = 15,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            SpeedGoal = 8,
                            TargetInputs = "[\"L_Pinky:Push\",\"L_Ring:Push\",\"L_Middle:Push\",\"L_Index:Push\",\"R_Index:Push\",\"R_Middle:Push\",\"R_Ring:Push\",\"R_Pinky:Push\"]",
                            Title = "Play: Push Keys",
                            Type = 3
                        },
                        new
                        {
                            Id = 16,
                            Content = "{\"videoUrl\":\"/videos/directions.mp4\",\"durationSeconds\":90,\"completionThreshold\":0.9}",
                            Description = "Learn the 4 directions: push, pull, east, and west",
                            Number = 1,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[]",
                            Title = "Directions Explained",
                            Type = 4
                        },
                        new
                        {
                            Id = 17,
                            Content = "{\"steps\":[{\"instruction\":\"Lift the left index switch upward to type r\",\"targetInput\":\"L_Index:Pull\",\"targetChar\":\"r\"}]}",
                            Description = "Pull the left index switch up to type r",
                            Number = 2,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_Index:Pull\"]",
                            Title = "Left Index Pull: r",
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            Content = "{\"steps\":[{\"instruction\":\"Lift the right index switch upward to type u\",\"targetInput\":\"R_Index:Pull\",\"targetChar\":\"u\"}]}",
                            Description = "Pull the right index switch up to type u",
                            Number = 3,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"R_Index:Pull\"]",
                            Title = "Right Index Pull: u",
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            Content = "{\"sequence\":[\"r\",\"u\",\"r\",\"u\",\"u\",\"r\",\"r\",\"u\",\"r\",\"u\",\"u\",\"r\",\"r\",\"u\",\"r\",\"u\",\"u\",\"r\",\"u\",\"r\"]}",
                            Description = "Practice r and u pull inputs",
                            Number = 4,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_Index:Pull\",\"R_Index:Pull\"]",
                            Title = "Review: r & u",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            Content = "{\"steps\":[{\"instruction\":\"Lift the left middle switch upward to type e\",\"targetInput\":\"L_Middle:Pull\",\"targetChar\":\"e\"}]}",
                            Description = "Pull the left middle switch up to type e",
                            Number = 5,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_Middle:Pull\"]",
                            Title = "Left Middle Pull: e",
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            Content = "{\"steps\":[{\"instruction\":\"Lift the right middle switch upward to type i\",\"targetInput\":\"R_Middle:Pull\",\"targetChar\":\"i\"}]}",
                            Description = "Pull the right middle switch up to type i",
                            Number = 6,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"R_Middle:Pull\"]",
                            Title = "Right Middle Pull: i",
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            Content = "{\"steps\":[{\"instruction\":\"Lift the left ring switch upward to type w\",\"targetInput\":\"L_Ring:Pull\",\"targetChar\":\"w\"}]}",
                            Description = "Pull the left ring switch up to type w",
                            Number = 7,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_Ring:Pull\"]",
                            Title = "Left Ring Pull: w",
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            Content = "{\"steps\":[{\"instruction\":\"Lift the right ring switch upward to type o\",\"targetInput\":\"R_Ring:Pull\",\"targetChar\":\"o\"}]}",
                            Description = "Pull the right ring switch up to type o",
                            Number = 8,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"R_Ring:Pull\"]",
                            Title = "Right Ring Pull: o",
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            Content = "{\"steps\":[{\"instruction\":\"Lift the left pinky switch upward to type q\",\"targetInput\":\"L_Pinky:Pull\",\"targetChar\":\"q\"}]}",
                            Description = "Pull the left pinky switch up to type q",
                            Number = 9,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_Pinky:Pull\"]",
                            Title = "Left Pinky Pull: q",
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            Content = "{\"steps\":[{\"instruction\":\"Lift the right pinky switch upward to type p\",\"targetInput\":\"R_Pinky:Pull\",\"targetChar\":\"p\"}]}",
                            Description = "Pull the right pinky switch up to type p",
                            Number = 10,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"R_Pinky:Pull\"]",
                            Title = "Right Pinky Pull: p",
                            Type = 0
                        },
                        new
                        {
                            Id = 26,
                            Content = "{\"sequence\":[\"r\",\"u\",\"e\",\"i\",\"w\",\"o\",\"q\",\"p\",\"e\",\"r\",\"i\",\"u\",\"w\",\"q\",\"o\",\"p\",\"r\",\"e\",\"u\",\"i\"]}",
                            Description = "Review all 8 pull inputs",
                            Number = 11,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_Index:Pull\",\"R_Index:Pull\",\"L_Middle:Pull\",\"R_Middle:Pull\",\"L_Ring:Pull\",\"R_Ring:Pull\",\"L_Pinky:Pull\",\"R_Pinky:Pull\"]",
                            Title = "Review: All Pull Keys",
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the left index switch to the right (east) to type t\",\"targetInput\":\"L_Index:East\",\"targetChar\":\"t\"},{\"instruction\":\"Tilt the left index switch to the left (west) to type g\",\"targetInput\":\"L_Index:West\",\"targetChar\":\"g\"}]}",
                            Description = "Tilt the left index east for t, west for g",
                            Number = 12,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_Index:East\",\"L_Index:West\"]",
                            Title = "Index East/West: t & g",
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the right index switch to the right (east) to type y\",\"targetInput\":\"R_Index:East\",\"targetChar\":\"y\"},{\"instruction\":\"Tilt the right index switch to the left (west) to type h\",\"targetInput\":\"R_Index:West\",\"targetChar\":\"h\"}]}",
                            Description = "Tilt the right index east for y, west for h",
                            Number = 13,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"R_Index:East\",\"R_Index:West\"]",
                            Title = "Index East/West: y & h",
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt left middle east to type c\",\"targetInput\":\"L_Middle:East\",\"targetChar\":\"c\"},{\"instruction\":\"Tilt left middle west to type b\",\"targetInput\":\"L_Middle:West\",\"targetChar\":\"b\"},{\"instruction\":\"Tilt right middle east to type ,\",\"targetInput\":\"R_Middle:East\",\"targetChar\":\",\"},{\"instruction\":\"Tilt right middle west to type n\",\"targetInput\":\"R_Middle:West\",\"targetChar\":\"n\"}]}",
                            Description = "Learn east and west tilts on middle fingers",
                            Number = 14,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_Middle:East\",\"L_Middle:West\",\"R_Middle:East\",\"R_Middle:West\"]",
                            Title = "Middle East/West: c, b, comma, n",
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt left ring east to type x\",\"targetInput\":\"L_Ring:East\",\"targetChar\":\"x\"},{\"instruction\":\"Tilt left ring west to type v\",\"targetInput\":\"L_Ring:West\",\"targetChar\":\"v\"},{\"instruction\":\"Tilt right ring east to type .\",\"targetInput\":\"R_Ring:East\",\"targetChar\":\".\"},{\"instruction\":\"Tilt right ring west to type m\",\"targetInput\":\"R_Ring:West\",\"targetChar\":\"m\"}]}",
                            Description = "Learn east and west tilts on ring and pinky fingers",
                            Number = 15,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_Ring:East\",\"L_Ring:West\",\"R_Ring:East\",\"R_Ring:West\"]",
                            Title = "Ring & Pinky East/West",
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            Content = "{\"text\":\"e r i u e i r u e r u i r e u i e u r i\",\"timeLimitSeconds\":120}",
                            Description = "Speed drill on the most common pull inputs",
                            Number = 16,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            SpeedGoal = 6,
                            TargetInputs = "[\"L_Middle:Pull\",\"L_Index:Pull\",\"R_Middle:Pull\",\"R_Index:Pull\"]",
                            Title = "Practice: e r i u",
                            Type = 2
                        },
                        new
                        {
                            Id = 32,
                            Content = "{\"text\":\"t y g h t h y g t g h y g t y h t y g h\",\"timeLimitSeconds\":120}",
                            Description = "Speed drill on common east/west inputs",
                            Number = 17,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            SpeedGoal = 5,
                            TargetInputs = "[\"L_Index:East\",\"R_Index:East\",\"L_Index:West\",\"R_Index:West\"]",
                            Title = "Practice: t y g h",
                            Type = 2
                        },
                        new
                        {
                            Id = 33,
                            Content = "{\"sequence\":[\"f\",\"r\",\"t\",\"g\",\"j\",\"u\",\"y\",\"h\",\"f\",\"u\",\"r\",\"j\",\"t\",\"y\",\"g\",\"h\"]}",
                            Description = "Mixed review of push, pull, east, and west",
                            Number = 18,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_Index:Push\",\"L_Index:Pull\",\"L_Index:East\",\"L_Index:West\",\"R_Index:Push\",\"R_Index:Pull\",\"R_Index:East\",\"R_Index:West\"]",
                            Title = "Review: All 4 Directions",
                            Type = 1
                        },
                        new
                        {
                            Id = 34,
                            Content = "{\"text\":\"fruit they grow hard if you are wet\",\"timeLimitSeconds\":90}",
                            Description = "Build speed across all directions",
                            Number = 19,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            SpeedGoal = 8,
                            TargetInputs = "[]",
                            Title = "Speed Drill: All Directions",
                            Type = 2
                        },
                        new
                        {
                            Id = 35,
                            Content = "{\"gameType\":\"falling-characters\",\"timeLimitSeconds\":60,\"wordPool\":[\"r\",\"u\",\"e\",\"i\",\"w\",\"o\",\"t\",\"y\",\"g\",\"h\",\"c\",\"b\"]}",
                            Description = "Game challenge — hit all 4 directions",
                            Number = 20,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            SpeedGoal = 10,
                            TargetInputs = "[]",
                            Title = "Play: Direction Challenge",
                            Type = 3
                        },
                        new
                        {
                            Id = 36,
                            Content = "{\"videoUrl\":\"/videos/cce.mp4\",\"durationSeconds\":90,\"completionThreshold\":0.9}",
                            Description = "Understand character-by-character entry and why speed matters",
                            Number = 1,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            TargetInputs = "[]",
                            Title = "CCE Typing Explained",
                            Type = 4
                        },
                        new
                        {
                            Id = 37,
                            Content = "{\"text\":\"as if of as of if as if of as if of as\",\"timeLimitSeconds\":90}",
                            Description = "Type short common words",
                            Number = 2,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 8,
                            TargetInputs = "[]",
                            Title = "Simple Words: as, if, of",
                            Type = 2
                        },
                        new
                        {
                            Id = 38,
                            Content = "{\"text\":\"all dad fall ask salad flask shall disk lid\",\"timeLimitSeconds\":90}",
                            Description = "Words using only home row push keys",
                            Number = 3,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 8,
                            TargetInputs = "[]",
                            Title = "Home Row Words",
                            Type = 2
                        },
                        new
                        {
                            Id = 39,
                            Content = "{\"text\":\"the and for are but not you all had her\",\"timeLimitSeconds\":90}",
                            Description = "Type the most common 3-letter words",
                            Number = 4,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 10,
                            TargetInputs = "[]",
                            Title = "Common 3-Letter Words",
                            Type = 2
                        },
                        new
                        {
                            Id = 40,
                            Content = "{\"sequence\":[\"the\",\"and\",\"for\",\"are\",\"you\",\"had\",\"her\",\"his\",\"its\",\"our\"]}",
                            Description = "Review short common words",
                            Number = 5,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            TargetInputs = "[]",
                            Title = "Review: Short Words",
                            Type = 1
                        },
                        new
                        {
                            Id = 41,
                            Content = "{\"text\":\"that with have this will your from they said each\",\"timeLimitSeconds\":90}",
                            Description = "Practice 4-letter common words",
                            Number = 6,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 10,
                            TargetInputs = "[]",
                            Title = "4-Letter Words",
                            Type = 2
                        },
                        new
                        {
                            Id = 42,
                            Content = "{\"text\":\"the quick red fox and the lazy dog sat still\",\"timeLimitSeconds\":60}",
                            Description = "Reach 10 WPM with common words",
                            Number = 7,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 10,
                            TargetInputs = "[]",
                            Title = "Speed Target: 10 WPM",
                            Type = 2
                        },
                        new
                        {
                            Id = 43,
                            Content = "{\"text\":\"in the and to a of it is was he for on are\",\"timeLimitSeconds\":90}",
                            Description = "Practice typing short phrases",
                            Number = 8,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 12,
                            TargetInputs = "[]",
                            Title = "Common Phrases",
                            Type = 2
                        },
                        new
                        {
                            Id = 44,
                            Content = "{\"text\":\"yes. no. wait; go. stop; run. sit. look; come.\",\"timeLimitSeconds\":90}",
                            Description = "Practice comma, period, and semicolons",
                            Number = 9,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 8,
                            TargetInputs = "[]",
                            Title = "Punctuation Basics",
                            Type = 2
                        },
                        new
                        {
                            Id = 45,
                            Content = "{\"text\":\"she was able to do the work and it felt right\",\"timeLimitSeconds\":60}",
                            Description = "Push your speed to 15 WPM",
                            Number = 10,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 15,
                            TargetInputs = "[]",
                            Title = "Speed Target: 15 WPM",
                            Type = 2
                        },
                        new
                        {
                            Id = 46,
                            Content = "{\"text\":\"the dog sat. she ran fast. he ate food. they slept.\",\"timeLimitSeconds\":90}",
                            Description = "Practice typing full short sentences",
                            Number = 11,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 12,
                            TargetInputs = "[]",
                            Title = "Common Sentences",
                            Type = 2
                        },
                        new
                        {
                            Id = 47,
                            Content = "{\"text\":\"to be or not to be that is the question here\",\"timeLimitSeconds\":60}",
                            Description = "Hit 20 WPM — a major CCE milestone",
                            Number = 12,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 20,
                            TargetInputs = "[]",
                            Title = "Speed Target: 20 WPM",
                            Type = 2
                        },
                        new
                        {
                            Id = 48,
                            Content = "{\"text\":\"work life time year day week made said great call\",\"timeLimitSeconds\":90}",
                            Description = "Random common words for consistency",
                            Number = 13,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 15,
                            TargetInputs = "[]",
                            Title = "Mixed Vocabulary Drill",
                            Type = 2
                        },
                        new
                        {
                            Id = 49,
                            Content = "{\"text\":\"she said the world is full of wonder and good things\",\"timeLimitSeconds\":120}",
                            Description = "Slow down and focus on zero errors",
                            Number = 14,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 10,
                            TargetInputs = "[]",
                            Title = "Accuracy Focus",
                            Type = 2
                        },
                        new
                        {
                            Id = 50,
                            Content = "{\"gameType\":\"word-race\",\"timeLimitSeconds\":60,\"wordPool\":[\"the\",\"and\",\"for\",\"you\",\"his\",\"her\",\"they\",\"have\",\"with\",\"this\",\"from\",\"that\",\"were\",\"said\",\"each\",\"when\",\"make\",\"like\",\"time\",\"just\"]}",
                            Description = "Race against the clock — how many words can you type?",
                            Number = 15,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 20,
                            TargetInputs = "[]",
                            Title = "Play: Word Race",
                            Type = 3
                        },
                        new
                        {
                            Id = 51,
                            Content = "{\"videoUrl\":\"/videos/chording-intro.mp4\",\"durationSeconds\":120,\"completionThreshold\":0.9}",
                            Description = "Learn how pressing multiple switches simultaneously types whole words",
                            Number = 1,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[]",
                            Title = "What is Chording?",
                            Type = 4
                        },
                        new
                        {
                            Id = 52,
                            Content = "{\"steps\":[{\"instruction\":\"Press left ring + left middle + left index simultaneously to type 'the'\",\"targetInput\":\"L_Ring:Push+L_Middle:Push+L_Index:Push\",\"targetChar\":\"the\"}]}",
                            Description = "Press three switches at once to type 'the'",
                            Number = 2,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"L_Ring:Push\",\"L_Middle:Push\",\"L_Index:Push\"]",
                            Title = "Your First Chord: the",
                            Type = 0
                        },
                        new
                        {
                            Id = 53,
                            Content = "{\"steps\":[{\"instruction\":\"Press left pinky + left ring + left middle simultaneously to type 'and'\",\"targetInput\":\"L_Pinky:Push+L_Ring:Push+L_Middle:Push\",\"targetChar\":\"and\"}]}",
                            Description = "Chord 'and' with left hand ring, middle, and pinky",
                            Number = 3,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"L_Ring:Push\",\"L_Middle:Push\",\"L_Pinky:Push\"]",
                            Title = "Chord: and",
                            Type = 0
                        },
                        new
                        {
                            Id = 54,
                            Content = "{\"steps\":[{\"instruction\":\"Press left index push + left middle pull simultaneously to type 'for'\",\"targetInput\":\"L_Index:Push+L_Middle:Pull\",\"targetChar\":\"for\"}]}",
                            Description = "Chord 'for' with index and middle fingers",
                            Number = 4,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"L_Index:Push\",\"L_Middle:Pull\"]",
                            Title = "Chord: for",
                            Type = 0
                        },
                        new
                        {
                            Id = 55,
                            Content = "{\"sequence\":[\"the\",\"and\",\"for\",\"the\",\"and\",\"for\",\"and\",\"the\",\"for\",\"the\",\"for\",\"and\"]}",
                            Description = "Practice your first three chords",
                            Number = 5,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[]",
                            Title = "Review: the, and, for",
                            Type = 1
                        },
                        new
                        {
                            Id = 56,
                            Content = "{\"steps\":[{\"instruction\":\"Press right index pull + right middle pull simultaneously to type 'you'\",\"targetInput\":\"R_Index:Pull+R_Middle:Pull\",\"targetChar\":\"you\"}]}",
                            Description = "Chord 'you' with right hand",
                            Number = 6,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"R_Index:Pull\",\"R_Middle:Pull\"]",
                            Title = "Chord: you",
                            Type = 0
                        },
                        new
                        {
                            Id = 57,
                            Content = "{\"steps\":[{\"instruction\":\"Press right ring pull + right index push simultaneously to type 'with'\",\"targetInput\":\"R_Ring:Pull+R_Index:Push\",\"targetChar\":\"with\"}]}",
                            Description = "Chord 'with' with right hand ring and index",
                            Number = 7,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"R_Ring:Pull\",\"R_Index:Push\"]",
                            Title = "Chord: with",
                            Type = 0
                        },
                        new
                        {
                            Id = 58,
                            Content = "{\"steps\":[{\"instruction\":\"Press left index east + left index push simultaneously to type 'that'\",\"targetInput\":\"L_Index:East+L_Index:Push\",\"targetChar\":\"that\"}]}",
                            Description = "Chord 'that' with left hand",
                            Number = 8,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"L_Index:East\",\"L_Index:Push\"]",
                            Title = "Chord: that",
                            Type = 0
                        },
                        new
                        {
                            Id = 59,
                            Content = "{\"text\":\"the and for you with that the with you and for that\",\"timeLimitSeconds\":90}",
                            Description = "Build speed with your first 6 chords",
                            Number = 9,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            SpeedGoal = 15,
                            TargetInputs = "[]",
                            Title = "Practice: First 6 Chords",
                            Type = 2
                        },
                        new
                        {
                            Id = 60,
                            Content = "{\"steps\":[{\"instruction\":\"Press left pinky push + left middle pull simultaneously to type 'have'\",\"targetInput\":\"L_Pinky:Push+L_Middle:Pull\",\"targetChar\":\"have\"}]}",
                            Description = "Chord 'have' with left pinky and middle",
                            Number = 10,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"L_Pinky:Push\",\"L_Middle:Pull\"]",
                            Title = "Chord: have",
                            Type = 0
                        },
                        new
                        {
                            Id = 61,
                            Content = "{\"steps\":[{\"instruction\":\"Press right ring push + right middle pull simultaneously to type 'this'\",\"targetInput\":\"R_Ring:Push+R_Middle:Pull\",\"targetChar\":\"this\"}]}",
                            Description = "Chord 'this' with right ring and middle",
                            Number = 11,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"R_Ring:Push\",\"R_Middle:Pull\"]",
                            Title = "Chord: this",
                            Type = 0
                        },
                        new
                        {
                            Id = 62,
                            Content = "{\"steps\":[{\"instruction\":\"Press left index pull + left ring push simultaneously to type 'from'\",\"targetInput\":\"L_Index:Pull+L_Ring:Push\",\"targetChar\":\"from\"}]}",
                            Description = "Chord 'from' with left fingers",
                            Number = 12,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"L_Index:Pull\",\"L_Ring:Push\"]",
                            Title = "Chord: from",
                            Type = 0
                        },
                        new
                        {
                            Id = 63,
                            Content = "{\"sequence\":[\"the\",\"and\",\"for\",\"you\",\"with\",\"that\",\"have\",\"this\",\"from\",\"the\",\"with\",\"you\",\"and\",\"that\",\"this\",\"have\",\"from\",\"for\"]}",
                            Description = "Review all chords learned so far",
                            Number = 13,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[]",
                            Title = "Review: All 9 Chords",
                            Type = 1
                        },
                        new
                        {
                            Id = 64,
                            Content = "{\"text\":\"the cat and you have this from that with the dog\",\"timeLimitSeconds\":60}",
                            Description = "Push chord speed to 20 WPM",
                            Number = 14,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            SpeedGoal = 20,
                            TargetInputs = "[]",
                            Title = "Speed Challenge: Basic Chords",
                            Type = 2
                        },
                        new
                        {
                            Id = 65,
                            Content = "{\"gameType\":\"word-race\",\"timeLimitSeconds\":60,\"wordPool\":[\"the\",\"and\",\"for\",\"you\",\"with\",\"that\",\"have\",\"this\",\"from\",\"they\",\"were\",\"said\"]}",
                            Description = "Game challenge — how fast can you chord?",
                            Number = 15,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            SpeedGoal = 25,
                            TargetInputs = "[]",
                            Title = "Play: Chord Race",
                            Type = 3
                        },
                        new
                        {
                            Id = 66,
                            Content = "{\"videoUrl\":\"/videos/advanced-chording.mp4\",\"durationSeconds\":120,\"completionThreshold\":0.9}",
                            Description = "Rolling chords, timing, and building a chord vocabulary",
                            Number = 1,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[]",
                            Title = "Advanced Chording Techniques",
                            Type = 4
                        },
                        new
                        {
                            Id = 67,
                            Content = "{\"steps\":[{\"instruction\":\"Press right index west + right ring pull simultaneously to type 'would'\",\"targetInput\":\"R_Index:West+R_Ring:Pull\",\"targetChar\":\"would\"}]}",
                            Description = "Chord 'would' with right hand",
                            Number = 2,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"R_Index:West\",\"R_Ring:Pull\"]",
                            Title = "Chord: would",
                            Type = 0
                        },
                        new
                        {
                            Id = 68,
                            Content = "{\"steps\":[{\"instruction\":\"Press right ring push + right index west simultaneously to type 'should'\",\"targetInput\":\"R_Ring:Push+R_Index:West\",\"targetChar\":\"should\"}]}",
                            Description = "Chord 'should' with right hand",
                            Number = 3,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"R_Ring:Push\",\"R_Index:West\"]",
                            Title = "Chord: should",
                            Type = 0
                        },
                        new
                        {
                            Id = 69,
                            Content = "{\"steps\":[{\"instruction\":\"Press left middle pull + left ring pull simultaneously to type 'could'\",\"targetInput\":\"L_Middle:Pull+L_Ring:Pull\",\"targetChar\":\"could\"}]}",
                            Description = "Chord 'could' with left hand",
                            Number = 4,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"L_Middle:Pull\",\"L_Ring:Pull\"]",
                            Title = "Chord: could",
                            Type = 0
                        },
                        new
                        {
                            Id = 70,
                            Content = "{\"sequence\":[\"would\",\"should\",\"could\",\"would\",\"could\",\"should\",\"should\",\"would\",\"could\",\"would\",\"should\",\"could\"]}",
                            Description = "Practice would, should, could",
                            Number = 5,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[]",
                            Title = "Review: Modal Verbs",
                            Type = 1
                        },
                        new
                        {
                            Id = 71,
                            Content = "{\"steps\":[{\"instruction\":\"Press right index push + right middle push + right ring pull simultaneously to type 'there'\",\"targetInput\":\"R_Index:Push+R_Middle:Push+R_Ring:Pull\",\"targetChar\":\"there\"}]}",
                            Description = "Chord 'there' with right fingers",
                            Number = 6,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"R_Index:Push\",\"R_Middle:Push\",\"R_Ring:Pull\"]",
                            Title = "Chord: there",
                            Type = 0
                        },
                        new
                        {
                            Id = 72,
                            Content = "{\"steps\":[{\"instruction\":\"Press right index pull + right middle push + right ring pull simultaneously to type 'their'\",\"targetInput\":\"R_Index:Pull+R_Middle:Push+R_Ring:Pull\",\"targetChar\":\"their\"}]}",
                            Description = "Chord 'their' — similar to 'there', different fingers",
                            Number = 7,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"R_Index:Pull\",\"R_Middle:Push\",\"R_Ring:Pull\"]",
                            Title = "Chord: their",
                            Type = 0
                        },
                        new
                        {
                            Id = 73,
                            Content = "{\"steps\":[{\"instruction\":\"Press right index push + right ring pull simultaneously to type 'they'\",\"targetInput\":\"R_Index:Push+R_Ring:Pull\",\"targetChar\":\"they\"}]}",
                            Description = "Chord 'they' with right hand",
                            Number = 8,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"R_Index:Push\",\"R_Ring:Pull\"]",
                            Title = "Chord: they",
                            Type = 0
                        },
                        new
                        {
                            Id = 74,
                            Content = "{\"text\":\"they would have the would you should be there their\",\"timeLimitSeconds\":90}",
                            Description = "Mix old and new chords for fluency",
                            Number = 9,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            SpeedGoal = 25,
                            TargetInputs = "[]",
                            Title = "Practice: Mixed Chords",
                            Type = 2
                        },
                        new
                        {
                            Id = 75,
                            Content = "{\"steps\":[{\"instruction\":\"Press left pinky push + right index pull + right middle pull simultaneously to type 'people'\",\"targetInput\":\"L_Pinky:Push+R_Index:Pull+R_Middle:Pull\",\"targetChar\":\"people\"}]}",
                            Description = "Chord 'people' with both hands",
                            Number = 10,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"L_Pinky:Push\",\"R_Index:Pull\",\"R_Middle:Pull\"]",
                            Title = "Chord: people",
                            Type = 0
                        },
                        new
                        {
                            Id = 76,
                            Content = "{\"steps\":[{\"instruction\":\"Press right index west + right middle pull simultaneously to type 'which'\",\"targetInput\":\"R_Index:West+R_Middle:Pull\",\"targetChar\":\"which\"}]}",
                            Description = "Chord 'which' with right hand",
                            Number = 11,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"R_Index:West\",\"R_Middle:Pull\"]",
                            Title = "Chord: which",
                            Type = 0
                        },
                        new
                        {
                            Id = 77,
                            Content = "{\"steps\":[{\"instruction\":\"Press left pinky pull + left middle push simultaneously to type 'about'\",\"targetInput\":\"L_Pinky:Pull+L_Middle:Push\",\"targetChar\":\"about\"}]}",
                            Description = "Chord 'about' with left hand",
                            Number = 12,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"L_Pinky:Pull\",\"L_Middle:Push\"]",
                            Title = "Chord: about",
                            Type = 0
                        },
                        new
                        {
                            Id = 78,
                            Content = "{\"text\":\"people which about would should could there their they\",\"timeLimitSeconds\":90}",
                            Description = "Speed drill with all advanced chords",
                            Number = 13,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            SpeedGoal = 30,
                            TargetInputs = "[]",
                            Title = "Practice: All Advanced Chords",
                            Type = 2
                        },
                        new
                        {
                            Id = 79,
                            Content = "{\"text\":\"the people would have said they should be there with you about which could be for all\",\"timeLimitSeconds\":60}",
                            Description = "Push for 40 WPM — elite CharaChorder speed",
                            Number = 14,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            SpeedGoal = 40,
                            TargetInputs = "[]",
                            Title = "Speed Target: 40 WPM",
                            Type = 2
                        },
                        new
                        {
                            Id = 80,
                            Content = "{\"gameType\":\"word-race\",\"timeLimitSeconds\":60,\"wordPool\":[\"the\",\"and\",\"for\",\"you\",\"with\",\"that\",\"have\",\"this\",\"from\",\"they\",\"would\",\"should\",\"could\",\"there\",\"their\",\"people\",\"which\",\"about\"]}",
                            Description = "Final game challenge — show off everything you have learned",
                            Number = 15,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            SpeedGoal = 40,
                            TargetInputs = "[]",
                            Title = "Play: Advanced Challenge",
                            Type = 3
                        });
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.LessonAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Accuracy")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputLog")
                        .HasColumnType("jsonb");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<decimal>("Speed")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("LessonAttempts");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Phases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Learn the push direction on all finger switches",
                            Name = "Switch Basics",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Master all 4 directional inputs across all switches",
                            Name = "Directional Inputs",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Build typing speed with character-by-character entry",
                            Name = "CCE Speed Building",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Learn to press multiple switches simultaneously for whole words",
                            Name = "Introduction to Chording",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Build chord vocabulary and speed for real-world proficiency",
                            Name = "Advanced Chording",
                            Order = 5
                        });
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.UserBadge", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.UserProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BestAccuracy")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("BestSpeed")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("BestStars")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FirstCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "LessonId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgress");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Lesson", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.Phase", "Phase")
                        .WithMany("Lessons")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.LessonAttempt", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.Lesson", "Lesson")
                        .WithMany("Attempts")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChordCraft.Core.Entities.User", "User")
                        .WithMany("Attempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.UserBadge", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChordCraft.Core.Entities.User", "User")
                        .WithMany("Badges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.UserProgress", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.Lesson", "Lesson")
                        .WithMany("UserProgress")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChordCraft.Core.Entities.User", "User")
                        .WithMany("Progress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChordCraft.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Lesson", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("UserProgress");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Phase", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.User", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Badges");

                    b.Navigation("Progress");
                });
#pragma warning restore 612, 618
        }
    }
}
