// <auto-generated />
using System;
using ChordCraft.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChordCraft.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319101521_FixCC2Layout")]
    partial class FixCC2Layout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChordCraft.Core.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Criteria = "{\"type\":\"first-lesson\"}",
                            Description = "Complete your first lesson",
                            IconUrl = "/images/badges/first-steps.svg",
                            Name = "First Steps"
                        },
                        new
                        {
                            Id = 2,
                            Criteria = "{\"type\":\"phase-complete\",\"phaseId\":1}",
                            Description = "Complete Phase 1",
                            IconUrl = "/images/badges/switch-basics.svg",
                            Name = "Switch Basics"
                        },
                        new
                        {
                            Id = 3,
                            Criteria = "{\"type\":\"phase-complete\",\"phaseId\":2}",
                            Description = "Complete Phase 2",
                            IconUrl = "/images/badges/direction-master.svg",
                            Name = "Direction Master"
                        },
                        new
                        {
                            Id = 4,
                            Criteria = "{\"type\":\"speed-threshold\",\"wpm\":20}",
                            Description = "Reach 20 WPM in a practice lesson",
                            IconUrl = "/images/badges/speed-demon.svg",
                            Name = "Speed Demon"
                        },
                        new
                        {
                            Id = 5,
                            Criteria = "{\"type\":\"first-chord\"}",
                            Description = "Successfully type your first chord",
                            IconUrl = "/images/badges/first-chord.svg",
                            Name = "First Chord"
                        },
                        new
                        {
                            Id = 6,
                            Criteria = "{\"type\":\"chord-count\",\"count\":10}",
                            Description = "Learn 10 different chords",
                            IconUrl = "/images/badges/chord-collector.svg",
                            Name = "Chord Collector"
                        },
                        new
                        {
                            Id = 7,
                            Criteria = "{\"type\":\"chord-count\",\"count\":50}",
                            Description = "Learn 50 different chords",
                            IconUrl = "/images/badges/chord-master.svg",
                            Name = "Chord Master"
                        },
                        new
                        {
                            Id = 8,
                            Criteria = "{\"type\":\"streak\",\"days\":5}",
                            Description = "Practice 5 days in a row",
                            IconUrl = "/images/badges/5-day-streak.svg",
                            Name = "5 Day Streak"
                        },
                        new
                        {
                            Id = 9,
                            Criteria = "{\"type\":\"weekend\"}",
                            Description = "Practice on Saturday and Sunday",
                            IconUrl = "/images/badges/weekend-warrior.svg",
                            Name = "Weekend Warrior"
                        },
                        new
                        {
                            Id = 10,
                            Criteria = "{\"type\":\"session-time\",\"minutes\":30}",
                            Description = "Practice for 30 minutes in one session",
                            IconUrl = "/images/badges/marathon-runner.svg",
                            Name = "Marathon Runner"
                        },
                        new
                        {
                            Id = 11,
                            Criteria = "{\"type\":\"star-count\",\"stars\":5,\"count\":10}",
                            Description = "Earn 5 stars on 10 lessons",
                            IconUrl = "/images/badges/perfectionist.svg",
                            Name = "Perfectionist"
                        },
                        new
                        {
                            Id = 12,
                            Criteria = "{\"type\":\"full-layout\"}",
                            Description = "Show proficiency on all 90 CCOS inputs",
                            IconUrl = "/images/badges/full-layout.svg",
                            Name = "Full Layout"
                        },
                        new
                        {
                            Id = 13,
                            Criteria = "{\"type\":\"daily-stars\",\"stars\":5,\"count\":5}",
                            Description = "Earn 5 stars on 5 lessons in one day",
                            IconUrl = "/images/badges/heavyweight.svg",
                            Name = "The Heavyweight"
                        },
                        new
                        {
                            Id = 14,
                            Criteria = "{\"type\":\"attempt-count\",\"count\":100}",
                            Description = "Rack up 100 total lesson attempts",
                            IconUrl = "/images/badges/keyboard-crusher.svg",
                            Name = "Keyboard Crusher"
                        });
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.ChordEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("InputKeys")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OutputText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChordEntries");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<decimal>("PassAccuracyThreshold")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<int>("PhaseId")
                        .HasColumnType("integer");

                    b.Property<int?>("SpeedGoal")
                        .HasColumnType("integer");

                    b.Property<string>("TargetInputs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "{\"videoUrl\":\"/videos/intro.mp4\",\"durationSeconds\":120,\"completionThreshold\":0.9}",
                            Description = "Learn what the CharaChorder 2 is and how to hold it",
                            Number = 1,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[]",
                            Title = "Introduction to CharaChorder 2",
                            Type = 4
                        },
                        new
                        {
                            Id = 2,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the left index switch south (toward you) to type e\",\"targetInput\":\"L_Index:Down\",\"targetChar\":\"e\"}]}",
                            Description = "Tilt the left index switch south (toward you) to type e",
                            Number = 2,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Index:Down\"]",
                            Title = "Left Index South: e",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the right index switch south (toward you) to type t\",\"targetInput\":\"R_Index:Down\",\"targetChar\":\"t\"}]}",
                            Description = "Tilt the right index switch south (toward you) to type t",
                            Number = 3,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"R_Index:Down\"]",
                            Title = "Right Index South: t",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Content = "{\"sequence\":[\"e\",\"t\",\"e\",\"t\",\"e\",\"e\",\"t\",\"t\",\"e\",\"t\",\"t\",\"e\",\"e\",\"t\",\"e\",\"t\",\"t\",\"e\",\"t\",\"e\"]}",
                            Description = "Practice typing e and t",
                            Number = 4,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Index:Down\",\"R_Index:Down\"]",
                            Title = "Review: e & t",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the right index switch west (to the left) to type a\",\"targetInput\":\"R_Index:Left\",\"targetChar\":\"a\"}]}",
                            Description = "Tilt the right index switch west (to the left) to type a",
                            Number = 5,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"R_Index:Left\"]",
                            Title = "Right Index West: a",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the right middle switch south (toward you) to type s\",\"targetInput\":\"R_Middle:Down\",\"targetChar\":\"s\"}]}",
                            Description = "Tilt the right middle switch south (toward you) to type s",
                            Number = 6,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"R_Middle:Down\"]",
                            Title = "Right Middle South: s",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Content = "{\"sequence\":[\"a\",\"s\",\"a\",\"s\",\"a\",\"a\",\"s\",\"s\",\"a\",\"s\",\"s\",\"a\",\"a\",\"s\",\"a\",\"s\",\"s\",\"a\",\"s\",\"a\"]}",
                            Description = "Practice typing a and s",
                            Number = 7,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"R_Index:Left\",\"R_Middle:Down\"]",
                            Title = "Review: a & s",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the left middle switch south (toward you) to type o\",\"targetInput\":\"L_Middle:Down\",\"targetChar\":\"o\"}]}",
                            Description = "Tilt the left middle switch south (toward you) to type o",
                            Number = 8,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Middle:Down\"]",
                            Title = "Left Middle South: o",
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the left index switch west (to the left) to type a space\",\"targetInput\":\"L_Index:Left\",\"targetChar\":\" \"}]}",
                            Description = "Tilt the left index switch west (to the left) to type a space",
                            Number = 9,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Index:Left\"]",
                            Title = "Left Index West: space",
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Content = "{\"sequence\":[\"o\",\" \",\"t\",\"o\",\" \",\"e\",\"o\",\" \",\"s\",\"o\",\" \",\"a\",\" \",\"o\",\" \",\"t\",\"o\",\" \",\"e\",\" \"]}",
                            Description = "Practice o and space",
                            Number = 10,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Middle:Down\",\"L_Index:Left\"]",
                            Title = "Review: o & space",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Content = "{\"text\":\"eat sea oat toe sat tea ate set eat oat sea toe sat\",\"timeLimitSeconds\":120}",
                            Description = "Build speed with your first five keys",
                            Number = 11,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            SpeedGoal = 5,
                            TargetInputs = "[]",
                            Title = "Practice: e t a s o",
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the left ring switch south (toward you) to type u\",\"targetInput\":\"L_Ring:Down\",\"targetChar\":\"u\"}]}",
                            Description = "Tilt the left ring switch south (toward you) to type u",
                            Number = 12,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Ring:Down\"]",
                            Title = "Left Ring South: u",
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the right ring switch south (toward you) to type n\",\"targetInput\":\"R_Ring:Down\",\"targetChar\":\"n\"}]}",
                            Description = "Tilt the right ring switch south (toward you) to type n",
                            Number = 13,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"R_Ring:Down\"]",
                            Title = "Right Ring South: n",
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            Content = "{\"sequence\":[\"u\",\"n\",\"u\",\"n\",\"u\",\"u\",\"n\",\"n\",\"u\",\"n\",\"n\",\"u\",\"u\",\"n\",\"u\",\"n\",\"n\",\"u\",\"n\",\"u\"]}",
                            Description = "Practice typing u and n",
                            Number = 14,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Ring:Down\",\"R_Ring:Down\"]",
                            Title = "Review: u & n",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Content = "{\"gameType\":\"falling-characters\",\"timeLimitSeconds\":60,\"wordPool\":[\"e\",\"t\",\"a\",\"s\",\"o\",\"u\",\"n\"]}",
                            Description = "Game challenge with all learned keys",
                            Number = 15,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            SpeedGoal = 8,
                            TargetInputs = "[]",
                            Title = "Play: South & West Tilts",
                            Type = 3
                        },
                        new
                        {
                            Id = 16,
                            Content = "{\"videoUrl\":\"/videos/directions.mp4\",\"durationSeconds\":90,\"completionThreshold\":0.9}",
                            Description = "Learn the north, east, and west tilt directions",
                            Number = 1,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[]",
                            Title = "Directions Explained",
                            Type = 4
                        },
                        new
                        {
                            Id = 17,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the left index switch east (to the right) to type r\",\"targetInput\":\"L_Index:Right\",\"targetChar\":\"r\"}]}",
                            Description = "Tilt the left index switch east (to the right) to type r",
                            Number = 2,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_Index:Right\"]",
                            Title = "Left Index East: r",
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the left middle switch east (to the right) to type i\",\"targetInput\":\"L_Middle:Right\",\"targetChar\":\"i\"}]}",
                            Description = "Tilt the left middle switch east (to the right) to type i",
                            Number = 3,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_Middle:Right\"]",
                            Title = "Left Middle East: i",
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            Content = "{\"sequence\":[\"r\",\"i\",\"r\",\"i\",\"i\",\"r\",\"r\",\"i\",\"r\",\"i\",\"i\",\"r\",\"r\",\"i\",\"r\",\"i\",\"i\",\"r\",\"i\",\"r\"]}",
                            Description = "Practice r and i",
                            Number = 4,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_Index:Right\",\"L_Middle:Right\"]",
                            Title = "Review: r & i",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the right middle switch north (away from you) to type y\",\"targetInput\":\"R_Middle:Up\",\"targetChar\":\"y\"}]}",
                            Description = "Tilt the right middle switch north (away from you) to type y",
                            Number = 5,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"R_Middle:Up\"]",
                            Title = "Right Middle North: y",
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the right middle switch west (to the left) to type j\",\"targetInput\":\"R_Middle:Left\",\"targetChar\":\"j\"}]}",
                            Description = "Tilt the right middle switch west (to the left) to type j",
                            Number = 6,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"R_Middle:Left\"]",
                            Title = "Right Middle West: j",
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            Content = "{\"sequence\":[\"y\",\"j\",\"y\",\"j\",\"j\",\"y\",\"y\",\"j\",\"y\",\"j\",\"j\",\"y\",\"y\",\"j\",\"y\",\"j\",\"j\",\"y\",\"j\",\"y\"]}",
                            Description = "Practice y and j",
                            Number = 7,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"R_Middle:Up\",\"R_Middle:Left\"]",
                            Title = "Review: y & j",
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the right thumb switch south (toward you) to type d\",\"targetInput\":\"R_ThumbInner:Down\",\"targetChar\":\"d\"},{\"instruction\":\"Tilt the right thumb switch north (away from you) to type p\",\"targetInput\":\"R_ThumbInner:Up\",\"targetChar\":\"p\"}]}",
                            Description = "Tilt the right thumb switch south for d, north for p",
                            Number = 8,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"R_ThumbInner:Down\",\"R_ThumbInner:Up\"]",
                            Title = "Right Thumb South & North: d & p",
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the right thumb switch east (to the right) to type h\",\"targetInput\":\"R_ThumbInner:Right\",\"targetChar\":\"h\"},{\"instruction\":\"Tilt the right thumb switch west (to the left) to type f\",\"targetInput\":\"R_ThumbInner:Left\",\"targetChar\":\"f\"}]}",
                            Description = "Tilt the right thumb switch east for h, west for f",
                            Number = 9,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"R_ThumbInner:Right\",\"R_ThumbInner:Left\"]",
                            Title = "Right Thumb East & West: h & f",
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            Content = "{\"sequence\":[\"p\",\"h\",\"d\",\"f\",\"h\",\"p\",\"f\",\"d\",\"p\",\"f\",\"h\",\"d\",\"f\",\"p\",\"d\",\"h\",\"p\",\"d\",\"f\",\"h\"]}",
                            Description = "Practice all four right thumb tilt directions",
                            Number = 10,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"R_ThumbInner:Up\",\"R_ThumbInner:Right\",\"R_ThumbInner:Down\",\"R_ThumbInner:Left\"]",
                            Title = "Review: p, h, d & f",
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the left thumb switch west (to the left) to type g\",\"targetInput\":\"L_ThumbInner:Left\",\"targetChar\":\"g\"},{\"instruction\":\"Tilt the left thumb switch east (to the right) to type w\",\"targetInput\":\"L_ThumbInner:Right\",\"targetChar\":\"w\"}]}",
                            Description = "Tilt the left thumb switch west for g, east for w",
                            Number = 11,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_ThumbInner:Left\",\"L_ThumbInner:Right\"]",
                            Title = "Left Thumb West & East: g & w",
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the left palm switch south (toward you) to type c\",\"targetInput\":\"L_PalmUpper:Down\",\"targetChar\":\"c\"}]}",
                            Description = "Tilt the left palm switch south (toward you) to type c",
                            Number = 12,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_PalmUpper:Down\"]",
                            Title = "Left Palm South: c",
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the left palm switch west (to the left) to type m\",\"targetInput\":\"L_PalmUpper:Left\",\"targetChar\":\"m\"}]}",
                            Description = "Tilt the left palm switch west (to the left) to type m",
                            Number = 13,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_PalmUpper:Left\"]",
                            Title = "Left Palm West: m",
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            Content = "{\"text\":\"the man can run and eat food if it is hot the cat sat and ate\",\"timeLimitSeconds\":120}",
                            Description = "Speed drill with all letters learned so far",
                            Number = 14,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            SpeedGoal = 6,
                            TargetInputs = "[]",
                            Title = "Practice: Common Letters",
                            Type = 2
                        },
                        new
                        {
                            Id = 30,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the right ring switch west (to the left) to type l\",\"targetInput\":\"R_Ring:Left\",\"targetChar\":\"l\"}]}",
                            Description = "Tilt the right ring switch west (to the left) to type l",
                            Number = 15,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"R_Ring:Left\"]",
                            Title = "Right Ring West: l",
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the left palm switch east (to the right) to type k\",\"targetInput\":\"L_PalmUpper:Right\",\"targetChar\":\"k\"}]}",
                            Description = "Tilt the left palm switch east (to the right) to type k",
                            Number = 16,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_PalmUpper:Right\"]",
                            Title = "Left Palm East: k",
                            Type = 0
                        },
                        new
                        {
                            Id = 32,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the left palm switch north (away from you) to type v\",\"targetInput\":\"L_PalmUpper:Up\",\"targetChar\":\"v\"}]}",
                            Description = "Tilt the left palm switch north (away from you) to type v",
                            Number = 17,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_PalmUpper:Up\"]",
                            Title = "Left Palm North: v",
                            Type = 0
                        },
                        new
                        {
                            Id = 33,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the left thumb switch south (toward you) to type z\",\"targetInput\":\"L_ThumbInner:Down\",\"targetChar\":\"z\"}]}",
                            Description = "Tilt the left thumb switch south (toward you) to type z",
                            Number = 18,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"L_ThumbInner:Down\"]",
                            Title = "Left Thumb South: z",
                            Type = 0
                        },
                        new
                        {
                            Id = 34,
                            Content = "{\"steps\":[{\"instruction\":\"Tilt the right palm switch north (away from you) to type x\",\"targetInput\":\"R_PalmUpper:Up\",\"targetChar\":\"x\"},{\"instruction\":\"Tilt the right palm switch west (to the left) to type b\",\"targetInput\":\"R_PalmUpper:Left\",\"targetChar\":\"b\"},{\"instruction\":\"Tilt the right palm switch south (toward you) to type q\",\"targetInput\":\"R_PalmUpper:Down\",\"targetChar\":\"q\"}]}",
                            Description = "Tilt the right palm switch for x, b, and q",
                            Number = 19,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            TargetInputs = "[\"R_PalmUpper:Up\",\"R_PalmUpper:Left\",\"R_PalmUpper:Down\"]",
                            Title = "Right Palm: x, b & q",
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            Content = "{\"gameType\":\"falling-characters\",\"timeLimitSeconds\":60,\"wordPool\":[\"r\",\"i\",\"y\",\"j\",\"d\",\"p\",\"h\",\"f\",\"g\",\"w\",\"c\",\"m\",\"l\",\"k\",\"v\",\"z\",\"x\",\"b\",\"q\"]}",
                            Description = "Game challenge — all tilt directions",
                            Number = 20,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 2,
                            SpeedGoal = 10,
                            TargetInputs = "[]",
                            Title = "Play: Direction Challenge",
                            Type = 3
                        },
                        new
                        {
                            Id = 36,
                            Content = "{\"videoUrl\":\"/videos/cce.mp4\",\"durationSeconds\":90,\"completionThreshold\":0.9}",
                            Description = "Understand character-by-character entry and why speed matters",
                            Number = 1,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            TargetInputs = "[]",
                            Title = "CCE Typing Explained",
                            Type = 4
                        },
                        new
                        {
                            Id = 37,
                            Content = "{\"text\":\"as if of as of if as if of as if of as\",\"timeLimitSeconds\":90}",
                            Description = "Type short common words",
                            Number = 2,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 8,
                            TargetInputs = "[]",
                            Title = "Simple Words: as, if, of",
                            Type = 2
                        },
                        new
                        {
                            Id = 38,
                            Content = "{\"text\":\"all dad fall ask salad flask shall disk lid\",\"timeLimitSeconds\":90}",
                            Description = "Words using only home row push keys",
                            Number = 3,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 8,
                            TargetInputs = "[]",
                            Title = "Home Row Words",
                            Type = 2
                        },
                        new
                        {
                            Id = 39,
                            Content = "{\"text\":\"the and for are but not you all had her\",\"timeLimitSeconds\":90}",
                            Description = "Type the most common 3-letter words",
                            Number = 4,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 10,
                            TargetInputs = "[]",
                            Title = "Common 3-Letter Words",
                            Type = 2
                        },
                        new
                        {
                            Id = 40,
                            Content = "{\"sequence\":[\"the\",\"and\",\"for\",\"are\",\"you\",\"had\",\"her\",\"his\",\"its\",\"our\"]}",
                            Description = "Review short common words",
                            Number = 5,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            TargetInputs = "[]",
                            Title = "Review: Short Words",
                            Type = 1
                        },
                        new
                        {
                            Id = 41,
                            Content = "{\"text\":\"that with have this will your from they said each\",\"timeLimitSeconds\":90}",
                            Description = "Practice 4-letter common words",
                            Number = 6,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 10,
                            TargetInputs = "[]",
                            Title = "4-Letter Words",
                            Type = 2
                        },
                        new
                        {
                            Id = 42,
                            Content = "{\"text\":\"the quick red fox and the lazy dog sat still\",\"timeLimitSeconds\":60}",
                            Description = "Reach 10 WPM with common words",
                            Number = 7,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 10,
                            TargetInputs = "[]",
                            Title = "Speed Target: 10 WPM",
                            Type = 2
                        },
                        new
                        {
                            Id = 43,
                            Content = "{\"text\":\"in the and to a of it is was he for on are\",\"timeLimitSeconds\":90}",
                            Description = "Practice typing short phrases",
                            Number = 8,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 12,
                            TargetInputs = "[]",
                            Title = "Common Phrases",
                            Type = 2
                        },
                        new
                        {
                            Id = 44,
                            Content = "{\"text\":\"yes. no. wait; go. stop; run. sit. look; come.\",\"timeLimitSeconds\":90}",
                            Description = "Practice comma, period, and semicolons",
                            Number = 9,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 8,
                            TargetInputs = "[]",
                            Title = "Punctuation Basics",
                            Type = 2
                        },
                        new
                        {
                            Id = 45,
                            Content = "{\"text\":\"she was able to do the work and it felt right\",\"timeLimitSeconds\":60}",
                            Description = "Push your speed to 15 WPM",
                            Number = 10,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 15,
                            TargetInputs = "[]",
                            Title = "Speed Target: 15 WPM",
                            Type = 2
                        },
                        new
                        {
                            Id = 46,
                            Content = "{\"text\":\"the dog sat. she ran fast. he ate food. they slept.\",\"timeLimitSeconds\":90}",
                            Description = "Practice typing full short sentences",
                            Number = 11,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 12,
                            TargetInputs = "[]",
                            Title = "Common Sentences",
                            Type = 2
                        },
                        new
                        {
                            Id = 47,
                            Content = "{\"text\":\"to be or not to be that is the question here\",\"timeLimitSeconds\":60}",
                            Description = "Hit 20 WPM — a major CCE milestone",
                            Number = 12,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 20,
                            TargetInputs = "[]",
                            Title = "Speed Target: 20 WPM",
                            Type = 2
                        },
                        new
                        {
                            Id = 48,
                            Content = "{\"text\":\"work life time year day week made said great call\",\"timeLimitSeconds\":90}",
                            Description = "Random common words for consistency",
                            Number = 13,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 15,
                            TargetInputs = "[]",
                            Title = "Mixed Vocabulary Drill",
                            Type = 2
                        },
                        new
                        {
                            Id = 49,
                            Content = "{\"text\":\"she said the world is full of wonder and good things\",\"timeLimitSeconds\":120}",
                            Description = "Slow down and focus on zero errors",
                            Number = 14,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 10,
                            TargetInputs = "[]",
                            Title = "Accuracy Focus",
                            Type = 2
                        },
                        new
                        {
                            Id = 50,
                            Content = "{\"gameType\":\"word-race\",\"timeLimitSeconds\":60,\"wordPool\":[\"the\",\"and\",\"for\",\"you\",\"his\",\"her\",\"they\",\"have\",\"with\",\"this\",\"from\",\"that\",\"were\",\"said\",\"each\",\"when\",\"make\",\"like\",\"time\",\"just\"]}",
                            Description = "Race against the clock — how many words can you type?",
                            Number = 15,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 3,
                            SpeedGoal = 20,
                            TargetInputs = "[]",
                            Title = "Play: Word Race",
                            Type = 3
                        },
                        new
                        {
                            Id = 51,
                            Content = "{\"videoUrl\":\"/videos/chording-intro.mp4\",\"durationSeconds\":120,\"completionThreshold\":0.9}",
                            Description = "Learn how pressing multiple switches simultaneously types whole words",
                            Number = 1,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[]",
                            Title = "What is Chording?",
                            Type = 4
                        },
                        new
                        {
                            Id = 52,
                            Content = "{\"steps\":[{\"instruction\":\"Press left ring + left middle + left index simultaneously to type 'the'\",\"targetInput\":\"L_Ring:Push+L_Middle:Push+L_Index:Push\",\"targetChar\":\"the\"}]}",
                            Description = "Press three switches at once to type 'the'",
                            Number = 2,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"L_Ring:Push\",\"L_Middle:Push\",\"L_Index:Push\"]",
                            Title = "Your First Chord: the",
                            Type = 0
                        },
                        new
                        {
                            Id = 53,
                            Content = "{\"steps\":[{\"instruction\":\"Press left pinky + left ring + left middle simultaneously to type 'and'\",\"targetInput\":\"L_Pinky:Push+L_Ring:Push+L_Middle:Push\",\"targetChar\":\"and\"}]}",
                            Description = "Chord 'and' with left hand ring, middle, and pinky",
                            Number = 3,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"L_Ring:Push\",\"L_Middle:Push\",\"L_Pinky:Push\"]",
                            Title = "Chord: and",
                            Type = 0
                        },
                        new
                        {
                            Id = 54,
                            Content = "{\"steps\":[{\"instruction\":\"Press left index push + left middle pull simultaneously to type 'for'\",\"targetInput\":\"L_Index:Push+L_Middle:Pull\",\"targetChar\":\"for\"}]}",
                            Description = "Chord 'for' with index and middle fingers",
                            Number = 4,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"L_Index:Push\",\"L_Middle:Pull\"]",
                            Title = "Chord: for",
                            Type = 0
                        },
                        new
                        {
                            Id = 55,
                            Content = "{\"sequence\":[\"the\",\"and\",\"for\",\"the\",\"and\",\"for\",\"and\",\"the\",\"for\",\"the\",\"for\",\"and\"]}",
                            Description = "Practice your first three chords",
                            Number = 5,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[]",
                            Title = "Review: the, and, for",
                            Type = 1
                        },
                        new
                        {
                            Id = 56,
                            Content = "{\"steps\":[{\"instruction\":\"Press right index pull + right middle pull simultaneously to type 'you'\",\"targetInput\":\"R_Index:Pull+R_Middle:Pull\",\"targetChar\":\"you\"}]}",
                            Description = "Chord 'you' with right hand",
                            Number = 6,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"R_Index:Pull\",\"R_Middle:Pull\"]",
                            Title = "Chord: you",
                            Type = 0
                        },
                        new
                        {
                            Id = 57,
                            Content = "{\"steps\":[{\"instruction\":\"Press right ring pull + right index push simultaneously to type 'with'\",\"targetInput\":\"R_Ring:Pull+R_Index:Push\",\"targetChar\":\"with\"}]}",
                            Description = "Chord 'with' with right hand ring and index",
                            Number = 7,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"R_Ring:Pull\",\"R_Index:Push\"]",
                            Title = "Chord: with",
                            Type = 0
                        },
                        new
                        {
                            Id = 58,
                            Content = "{\"steps\":[{\"instruction\":\"Press left index east + left index push simultaneously to type 'that'\",\"targetInput\":\"L_Index:East+L_Index:Push\",\"targetChar\":\"that\"}]}",
                            Description = "Chord 'that' with left hand",
                            Number = 8,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"L_Index:East\",\"L_Index:Push\"]",
                            Title = "Chord: that",
                            Type = 0
                        },
                        new
                        {
                            Id = 59,
                            Content = "{\"text\":\"the and for you with that the with you and for that\",\"timeLimitSeconds\":90}",
                            Description = "Build speed with your first 6 chords",
                            Number = 9,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            SpeedGoal = 15,
                            TargetInputs = "[]",
                            Title = "Practice: First 6 Chords",
                            Type = 2
                        },
                        new
                        {
                            Id = 60,
                            Content = "{\"steps\":[{\"instruction\":\"Press left pinky push + left middle pull simultaneously to type 'have'\",\"targetInput\":\"L_Pinky:Push+L_Middle:Pull\",\"targetChar\":\"have\"}]}",
                            Description = "Chord 'have' with left pinky and middle",
                            Number = 10,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"L_Pinky:Push\",\"L_Middle:Pull\"]",
                            Title = "Chord: have",
                            Type = 0
                        },
                        new
                        {
                            Id = 61,
                            Content = "{\"steps\":[{\"instruction\":\"Press right ring push + right middle pull simultaneously to type 'this'\",\"targetInput\":\"R_Ring:Push+R_Middle:Pull\",\"targetChar\":\"this\"}]}",
                            Description = "Chord 'this' with right ring and middle",
                            Number = 11,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"R_Ring:Push\",\"R_Middle:Pull\"]",
                            Title = "Chord: this",
                            Type = 0
                        },
                        new
                        {
                            Id = 62,
                            Content = "{\"steps\":[{\"instruction\":\"Press left index pull + left ring push simultaneously to type 'from'\",\"targetInput\":\"L_Index:Pull+L_Ring:Push\",\"targetChar\":\"from\"}]}",
                            Description = "Chord 'from' with left fingers",
                            Number = 12,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[\"L_Index:Pull\",\"L_Ring:Push\"]",
                            Title = "Chord: from",
                            Type = 0
                        },
                        new
                        {
                            Id = 63,
                            Content = "{\"sequence\":[\"the\",\"and\",\"for\",\"you\",\"with\",\"that\",\"have\",\"this\",\"from\",\"the\",\"with\",\"you\",\"and\",\"that\",\"this\",\"have\",\"from\",\"for\"]}",
                            Description = "Review all chords learned so far",
                            Number = 13,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            TargetInputs = "[]",
                            Title = "Review: All 9 Chords",
                            Type = 1
                        },
                        new
                        {
                            Id = 64,
                            Content = "{\"text\":\"the cat and you have this from that with the dog\",\"timeLimitSeconds\":60}",
                            Description = "Push chord speed to 20 WPM",
                            Number = 14,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            SpeedGoal = 20,
                            TargetInputs = "[]",
                            Title = "Speed Challenge: Basic Chords",
                            Type = 2
                        },
                        new
                        {
                            Id = 65,
                            Content = "{\"gameType\":\"word-race\",\"timeLimitSeconds\":60,\"wordPool\":[\"the\",\"and\",\"for\",\"you\",\"with\",\"that\",\"have\",\"this\",\"from\",\"they\",\"were\",\"said\"]}",
                            Description = "Game challenge — how fast can you chord?",
                            Number = 15,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 4,
                            SpeedGoal = 25,
                            TargetInputs = "[]",
                            Title = "Play: Chord Race",
                            Type = 3
                        },
                        new
                        {
                            Id = 66,
                            Content = "{\"videoUrl\":\"/videos/advanced-chording.mp4\",\"durationSeconds\":120,\"completionThreshold\":0.9}",
                            Description = "Rolling chords, timing, and building a chord vocabulary",
                            Number = 1,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[]",
                            Title = "Advanced Chording Techniques",
                            Type = 4
                        },
                        new
                        {
                            Id = 67,
                            Content = "{\"steps\":[{\"instruction\":\"Press right index west + right ring pull simultaneously to type 'would'\",\"targetInput\":\"R_Index:West+R_Ring:Pull\",\"targetChar\":\"would\"}]}",
                            Description = "Chord 'would' with right hand",
                            Number = 2,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"R_Index:West\",\"R_Ring:Pull\"]",
                            Title = "Chord: would",
                            Type = 0
                        },
                        new
                        {
                            Id = 68,
                            Content = "{\"steps\":[{\"instruction\":\"Press right ring push + right index west simultaneously to type 'should'\",\"targetInput\":\"R_Ring:Push+R_Index:West\",\"targetChar\":\"should\"}]}",
                            Description = "Chord 'should' with right hand",
                            Number = 3,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"R_Ring:Push\",\"R_Index:West\"]",
                            Title = "Chord: should",
                            Type = 0
                        },
                        new
                        {
                            Id = 69,
                            Content = "{\"steps\":[{\"instruction\":\"Press left middle pull + left ring pull simultaneously to type 'could'\",\"targetInput\":\"L_Middle:Pull+L_Ring:Pull\",\"targetChar\":\"could\"}]}",
                            Description = "Chord 'could' with left hand",
                            Number = 4,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"L_Middle:Pull\",\"L_Ring:Pull\"]",
                            Title = "Chord: could",
                            Type = 0
                        },
                        new
                        {
                            Id = 70,
                            Content = "{\"sequence\":[\"would\",\"should\",\"could\",\"would\",\"could\",\"should\",\"should\",\"would\",\"could\",\"would\",\"should\",\"could\"]}",
                            Description = "Practice would, should, could",
                            Number = 5,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[]",
                            Title = "Review: Modal Verbs",
                            Type = 1
                        },
                        new
                        {
                            Id = 71,
                            Content = "{\"steps\":[{\"instruction\":\"Press right index push + right middle push + right ring pull simultaneously to type 'there'\",\"targetInput\":\"R_Index:Push+R_Middle:Push+R_Ring:Pull\",\"targetChar\":\"there\"}]}",
                            Description = "Chord 'there' with right fingers",
                            Number = 6,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"R_Index:Push\",\"R_Middle:Push\",\"R_Ring:Pull\"]",
                            Title = "Chord: there",
                            Type = 0
                        },
                        new
                        {
                            Id = 72,
                            Content = "{\"steps\":[{\"instruction\":\"Press right index pull + right middle push + right ring pull simultaneously to type 'their'\",\"targetInput\":\"R_Index:Pull+R_Middle:Push+R_Ring:Pull\",\"targetChar\":\"their\"}]}",
                            Description = "Chord 'their' — similar to 'there', different fingers",
                            Number = 7,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"R_Index:Pull\",\"R_Middle:Push\",\"R_Ring:Pull\"]",
                            Title = "Chord: their",
                            Type = 0
                        },
                        new
                        {
                            Id = 73,
                            Content = "{\"steps\":[{\"instruction\":\"Press right index push + right ring pull simultaneously to type 'they'\",\"targetInput\":\"R_Index:Push+R_Ring:Pull\",\"targetChar\":\"they\"}]}",
                            Description = "Chord 'they' with right hand",
                            Number = 8,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"R_Index:Push\",\"R_Ring:Pull\"]",
                            Title = "Chord: they",
                            Type = 0
                        },
                        new
                        {
                            Id = 74,
                            Content = "{\"text\":\"they would have the would you should be there their\",\"timeLimitSeconds\":90}",
                            Description = "Mix old and new chords for fluency",
                            Number = 9,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            SpeedGoal = 25,
                            TargetInputs = "[]",
                            Title = "Practice: Mixed Chords",
                            Type = 2
                        },
                        new
                        {
                            Id = 75,
                            Content = "{\"steps\":[{\"instruction\":\"Press left pinky push + right index pull + right middle pull simultaneously to type 'people'\",\"targetInput\":\"L_Pinky:Push+R_Index:Pull+R_Middle:Pull\",\"targetChar\":\"people\"}]}",
                            Description = "Chord 'people' with both hands",
                            Number = 10,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"L_Pinky:Push\",\"R_Index:Pull\",\"R_Middle:Pull\"]",
                            Title = "Chord: people",
                            Type = 0
                        },
                        new
                        {
                            Id = 76,
                            Content = "{\"steps\":[{\"instruction\":\"Press right index west + right middle pull simultaneously to type 'which'\",\"targetInput\":\"R_Index:West+R_Middle:Pull\",\"targetChar\":\"which\"}]}",
                            Description = "Chord 'which' with right hand",
                            Number = 11,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"R_Index:West\",\"R_Middle:Pull\"]",
                            Title = "Chord: which",
                            Type = 0
                        },
                        new
                        {
                            Id = 77,
                            Content = "{\"steps\":[{\"instruction\":\"Press left pinky pull + left middle push simultaneously to type 'about'\",\"targetInput\":\"L_Pinky:Pull+L_Middle:Push\",\"targetChar\":\"about\"}]}",
                            Description = "Chord 'about' with left hand",
                            Number = 12,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            TargetInputs = "[\"L_Pinky:Pull\",\"L_Middle:Push\"]",
                            Title = "Chord: about",
                            Type = 0
                        },
                        new
                        {
                            Id = 78,
                            Content = "{\"text\":\"people which about would should could there their they\",\"timeLimitSeconds\":90}",
                            Description = "Speed drill with all advanced chords",
                            Number = 13,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            SpeedGoal = 30,
                            TargetInputs = "[]",
                            Title = "Practice: All Advanced Chords",
                            Type = 2
                        },
                        new
                        {
                            Id = 79,
                            Content = "{\"text\":\"the people would have said they should be there with you about which could be for all\",\"timeLimitSeconds\":60}",
                            Description = "Push for 40 WPM — elite CharaChorder speed",
                            Number = 14,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            SpeedGoal = 40,
                            TargetInputs = "[]",
                            Title = "Speed Target: 40 WPM",
                            Type = 2
                        },
                        new
                        {
                            Id = 80,
                            Content = "{\"gameType\":\"word-race\",\"timeLimitSeconds\":60,\"wordPool\":[\"the\",\"and\",\"for\",\"you\",\"with\",\"that\",\"have\",\"this\",\"from\",\"they\",\"would\",\"should\",\"could\",\"there\",\"their\",\"people\",\"which\",\"about\"]}",
                            Description = "Final game challenge — show off everything you have learned",
                            Number = 15,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 5,
                            SpeedGoal = 40,
                            TargetInputs = "[]",
                            Title = "Play: Advanced Challenge",
                            Type = 3
                        });
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.LessonAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Accuracy")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputLog")
                        .HasColumnType("jsonb");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<decimal>("Speed")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("LessonAttempts");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Phases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Learn the push direction on all finger switches",
                            Name = "Switch Basics",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Master all 4 directional inputs across all switches",
                            Name = "Directional Inputs",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Build typing speed with character-by-character entry",
                            Name = "CCE Speed Building",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Learn to press multiple switches simultaneously for whole words",
                            Name = "Introduction to Chording",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Build chord vocabulary and speed for real-world proficiency",
                            Name = "Advanced Chording",
                            Order = 5
                        });
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.UserBadge", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.UserProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BestAccuracy")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("BestSpeed")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("BestStars")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FirstCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "LessonId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgress");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Lesson", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.Phase", "Phase")
                        .WithMany("Lessons")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.LessonAttempt", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.Lesson", "Lesson")
                        .WithMany("Attempts")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChordCraft.Core.Entities.User", "User")
                        .WithMany("Attempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.UserBadge", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChordCraft.Core.Entities.User", "User")
                        .WithMany("Badges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.UserProgress", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.Lesson", "Lesson")
                        .WithMany("UserProgress")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChordCraft.Core.Entities.User", "User")
                        .WithMany("Progress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChordCraft.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Lesson", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("UserProgress");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Phase", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.User", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Badges");

                    b.Navigation("Progress");
                });
#pragma warning restore 612, 618
        }
    }
}
