// <auto-generated />
using System;
using ChordCraft.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChordCraft.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChordCraft.Core.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Criteria = "{\"type\":\"first-lesson\"}",
                            Description = "Complete your first lesson",
                            IconUrl = "/images/badges/first-steps.svg",
                            Name = "First Steps"
                        },
                        new
                        {
                            Id = 2,
                            Criteria = "{\"type\":\"phase-complete\",\"phaseId\":1}",
                            Description = "Complete Phase 1",
                            IconUrl = "/images/badges/switch-basics.svg",
                            Name = "Switch Basics"
                        },
                        new
                        {
                            Id = 3,
                            Criteria = "{\"type\":\"phase-complete\",\"phaseId\":2}",
                            Description = "Complete Phase 2",
                            IconUrl = "/images/badges/direction-master.svg",
                            Name = "Direction Master"
                        },
                        new
                        {
                            Id = 4,
                            Criteria = "{\"type\":\"speed-threshold\",\"wpm\":20}",
                            Description = "Reach 20 WPM in a practice lesson",
                            IconUrl = "/images/badges/speed-demon.svg",
                            Name = "Speed Demon"
                        },
                        new
                        {
                            Id = 5,
                            Criteria = "{\"type\":\"first-chord\"}",
                            Description = "Successfully type your first chord",
                            IconUrl = "/images/badges/first-chord.svg",
                            Name = "First Chord"
                        },
                        new
                        {
                            Id = 6,
                            Criteria = "{\"type\":\"chord-count\",\"count\":10}",
                            Description = "Learn 10 different chords",
                            IconUrl = "/images/badges/chord-collector.svg",
                            Name = "Chord Collector"
                        },
                        new
                        {
                            Id = 7,
                            Criteria = "{\"type\":\"chord-count\",\"count\":50}",
                            Description = "Learn 50 different chords",
                            IconUrl = "/images/badges/chord-master.svg",
                            Name = "Chord Master"
                        },
                        new
                        {
                            Id = 8,
                            Criteria = "{\"type\":\"streak\",\"days\":5}",
                            Description = "Practice 5 days in a row",
                            IconUrl = "/images/badges/5-day-streak.svg",
                            Name = "5 Day Streak"
                        },
                        new
                        {
                            Id = 9,
                            Criteria = "{\"type\":\"weekend\"}",
                            Description = "Practice on Saturday and Sunday",
                            IconUrl = "/images/badges/weekend-warrior.svg",
                            Name = "Weekend Warrior"
                        },
                        new
                        {
                            Id = 10,
                            Criteria = "{\"type\":\"session-time\",\"minutes\":30}",
                            Description = "Practice for 30 minutes in one session",
                            IconUrl = "/images/badges/marathon-runner.svg",
                            Name = "Marathon Runner"
                        },
                        new
                        {
                            Id = 11,
                            Criteria = "{\"type\":\"star-count\",\"stars\":5,\"count\":10}",
                            Description = "Earn 5 stars on 10 lessons",
                            IconUrl = "/images/badges/perfectionist.svg",
                            Name = "Perfectionist"
                        },
                        new
                        {
                            Id = 12,
                            Criteria = "{\"type\":\"full-layout\"}",
                            Description = "Show proficiency on all 90 CCOS inputs",
                            IconUrl = "/images/badges/full-layout.svg",
                            Name = "Full Layout"
                        },
                        new
                        {
                            Id = 13,
                            Criteria = "{\"type\":\"daily-stars\",\"stars\":5,\"count\":5}",
                            Description = "Earn 5 stars on 5 lessons in one day",
                            IconUrl = "/images/badges/heavyweight.svg",
                            Name = "The Heavyweight"
                        },
                        new
                        {
                            Id = 14,
                            Criteria = "{\"type\":\"attempt-count\",\"count\":100}",
                            Description = "Rack up 100 total lesson attempts",
                            IconUrl = "/images/badges/keyboard-crusher.svg",
                            Name = "Keyboard Crusher"
                        });
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.ChordEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("InputKeys")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OutputText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChordEntries");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<decimal>("PassAccuracyThreshold")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<int>("PhaseId")
                        .HasColumnType("integer");

                    b.Property<int?>("SpeedGoal")
                        .HasColumnType("integer");

                    b.Property<string>("TargetInputs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "{\"videoUrl\":\"/videos/intro.mp4\",\"durationSeconds\":120,\"completionThreshold\":0.9}",
                            Description = "Learn what the CharaChorder One is and how to hold it",
                            Number = 1,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[]",
                            Title = "Introduction to CharaChorder",
                            Type = 4
                        },
                        new
                        {
                            Id = 2,
                            Content = "{\"steps\":[{\"instruction\":\"Push the left index switch down to type f\",\"targetInput\":\"L_Index:Push\",\"targetChar\":\"f\"}]}",
                            Description = "Push the left index switch to type f",
                            Number = 2,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Index:Push\"]",
                            Title = "Left Index Push: f",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Content = "{\"steps\":[{\"instruction\":\"Push the right index switch down to type j\",\"targetInput\":\"R_Index:Push\",\"targetChar\":\"j\"}]}",
                            Description = "Push the right index switch to type j",
                            Number = 3,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"R_Index:Push\"]",
                            Title = "Right Index Push: j",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Content = "{\"sequence\":[\"f\",\"j\",\"f\",\"j\",\"f\",\"f\",\"j\",\"j\",\"f\",\"j\",\"j\",\"f\",\"f\",\"j\",\"f\",\"j\",\"j\",\"f\",\"j\",\"f\"]}",
                            Description = "Practice typing f and j",
                            Number = 4,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Index:Push\",\"R_Index:Push\"]",
                            Title = "Review: f & j",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "{\"steps\":[{\"instruction\":\"Push the left thumb switch to type a space\",\"targetInput\":\"L_Thumb:Push\",\"targetChar\":\" \"}]}",
                            Description = "Push the left thumb switch for space",
                            Number = 5,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Thumb:Push\"]",
                            Title = "Space (Left Thumb Push)",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Content = "{\"steps\":[{\"instruction\":\"Push the left middle switch down to type d\",\"targetInput\":\"L_Middle:Push\",\"targetChar\":\"d\"}]}",
                            Description = "Push the left middle switch to type d",
                            Number = 6,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Middle:Push\"]",
                            Title = "Left Middle Push: d",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Content = "{\"steps\":[{\"instruction\":\"Push the right middle switch down to type k\",\"targetInput\":\"R_Middle:Push\",\"targetChar\":\"k\"}]}",
                            Description = "Push the right middle switch to type k",
                            Number = 7,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"R_Middle:Push\"]",
                            Title = "Right Middle Push: k",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Content = "{\"sequence\":[\"d\",\"k\",\"d\",\"k\",\"d\",\"d\",\"k\",\"k\",\"d\",\"k\",\"k\",\"d\",\"d\",\"k\",\"d\",\"k\",\"k\",\"d\",\"k\",\"d\"]}",
                            Description = "Practice typing d and k",
                            Number = 8,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Middle:Push\",\"R_Middle:Push\"]",
                            Title = "Review: d & k",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Content = "{\"text\":\"f j d k f k d j f d k j d f j k f j d k\",\"timeLimitSeconds\":120}",
                            Description = "Practice all four keys together",
                            Number = 9,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            SpeedGoal = 5,
                            TargetInputs = "[\"L_Index:Push\",\"R_Index:Push\",\"L_Middle:Push\",\"R_Middle:Push\"]",
                            Title = "Practice: f j d k",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Content = "{\"steps\":[{\"instruction\":\"Push the left ring switch down to type s\",\"targetInput\":\"L_Ring:Push\",\"targetChar\":\"s\"}]}",
                            Description = "Push the left ring switch to type s",
                            Number = 10,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Ring:Push\"]",
                            Title = "Left Ring Push: s",
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            Content = "{\"steps\":[{\"instruction\":\"Push the right ring switch down to type l\",\"targetInput\":\"R_Ring:Push\",\"targetChar\":\"l\"}]}",
                            Description = "Push the right ring switch to type l",
                            Number = 11,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"R_Ring:Push\"]",
                            Title = "Right Ring Push: l",
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Content = "{\"steps\":[{\"instruction\":\"Push the left pinky switch down to type a\",\"targetInput\":\"L_Pinky:Push\",\"targetChar\":\"a\"}]}",
                            Description = "Push the left pinky switch to type a",
                            Number = 12,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Pinky:Push\"]",
                            Title = "Left Pinky Push: a",
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Content = "{\"steps\":[{\"instruction\":\"Push the right pinky switch down to type ;\",\"targetInput\":\"R_Pinky:Push\",\"targetChar\":\";\"}]}",
                            Description = "Push the right pinky switch to type ;",
                            Number = 13,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"R_Pinky:Push\"]",
                            Title = "Right Pinky Push: ;",
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            Content = "{\"sequence\":[\"a\",\"s\",\"d\",\"f\",\"j\",\"k\",\"l\",\";\",\"f\",\"j\",\"a\",\";\",\"s\",\"l\",\"d\",\"k\"]}",
                            Description = "Review all finger push inputs",
                            Number = 14,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            TargetInputs = "[\"L_Pinky:Push\",\"L_Ring:Push\",\"L_Middle:Push\",\"L_Index:Push\",\"R_Index:Push\",\"R_Middle:Push\",\"R_Ring:Push\",\"R_Pinky:Push\"]",
                            Title = "All Push Keys",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Content = "{\"gameType\":\"falling-characters\",\"timeLimitSeconds\":60,\"wordPool\":[\"a\",\"s\",\"d\",\"f\",\"j\",\"k\",\"l\",\";\"]}",
                            Description = "Game challenge with push keys",
                            Number = 15,
                            PassAccuracyThreshold = 0.80m,
                            PhaseId = 1,
                            SpeedGoal = 8,
                            TargetInputs = "[\"L_Pinky:Push\",\"L_Ring:Push\",\"L_Middle:Push\",\"L_Index:Push\",\"R_Index:Push\",\"R_Middle:Push\",\"R_Ring:Push\",\"R_Pinky:Push\"]",
                            Title = "Play: Push Keys",
                            Type = 3
                        });
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.LessonAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Accuracy")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputLog")
                        .HasColumnType("jsonb");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<decimal>("Speed")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("LessonAttempts");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Phases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Learn the push direction on all finger switches",
                            Name = "Switch Basics",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Master all 4 directional inputs across all switches",
                            Name = "Directional Inputs",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Build typing speed with character-by-character entry",
                            Name = "CCE Speed Building",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Learn to press multiple switches simultaneously for whole words",
                            Name = "Introduction to Chording",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Build chord vocabulary and speed for real-world proficiency",
                            Name = "Advanced Chording",
                            Order = 5
                        });
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.UserBadge", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.UserProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BestAccuracy")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("BestSpeed")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("BestStars")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FirstCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "LessonId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgress");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Lesson", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.Phase", "Phase")
                        .WithMany("Lessons")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.LessonAttempt", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.Lesson", "Lesson")
                        .WithMany("Attempts")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChordCraft.Core.Entities.User", "User")
                        .WithMany("Attempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.UserBadge", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChordCraft.Core.Entities.User", "User")
                        .WithMany("Badges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.UserProgress", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.Lesson", "Lesson")
                        .WithMany("UserProgress")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChordCraft.Core.Entities.User", "User")
                        .WithMany("Progress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChordCraft.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ChordCraft.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Lesson", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("UserProgress");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.Phase", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ChordCraft.Core.Entities.User", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Badges");

                    b.Navigation("Progress");
                });
#pragma warning restore 612, 618
        }
    }
}
